spring:
  profiles:
    active: deleteMe

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  profiles: dev

---
# Coloque aqui suas configurações de Homologação
spring:
  profiles: homo

---
spring:
  profiles: deleteMe
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres2018!